package inject

// Inject is a placeholder function whose implementation is generated by the 'inject' command.
func Inject[R any](ret R) {
	panic("not implemented")
}

// InjectE is a placeholder function whose implementation is generated by the 'inject' command.
func InjectE[R any](ret R, err error) {
	panic("not implemented")
}

// InjectC is a placeholder function whose implementation is generated by the 'inject' command.
func InjectC[R any](ret R, cleanup func()) {
	panic("not implemented")
}

// InjectCE is a placeholder function whose implementation is generated by the 'inject' command.
func InjectCE[R any](ret R, cleanup func(), err error) {
	panic("not implemented")
}

// Inject2 is a placeholder function whose implementation is generated by the 'inject' command.
func Inject2[R1, R2 any](ret1 R1, ret2 R2) {
	panic("not implemented")
}

// Inject2E is a placeholder function whose implementation is generated by the 'inject' command.
func Inject2E[R1, R2 any](ret1 R1, ret2 R2, err error) {
	panic("not implemented")
}

// Inject2C is a placeholder function whose implementation is generated by the 'inject' command.
func Inject2C[R1, R2 any](ret1 R1, ret2 R2, cleanup func()) {
	panic("not implemented")
}

// Inject2CE is a placeholder function whose implementation is generated by the 'inject' command.
func Inject2CE[R1, R2 any](ret1 R1, ret2 R2, cleanup func(), err error) {
	panic("not implemented")
}

// Inject3 is a placeholder function whose implementation is generated by the 'inject' command.
func Inject3[R1, R2, R3 any](ret1 R1, ret2 R2, ret3 R3) {
	panic("not implemented")
}

// Inject3E is a placeholder function whose implementation is generated by the 'inject' command.
func Inject3E[R1, R2, R3 any](ret1 R1, ret2 R2, ret3 R3, err error) {
	panic("not implemented")
}

// Inject3C is a placeholder function whose implementation is generated by the 'inject' command.
func Inject3C[R1, R2, R3 any](ret1 R1, ret2 R2, ret3 R3, cleanup func()) {
	panic("not implemented")
}

// Inject3CE is a placeholder function whose implementation is generated by the 'inject' command.
func Inject3CE[R1, R2, R3 any](ret1 R1, ret2 R2, ret3 R3, cleanup func(), err error) {
	panic("not implemented")
}

// Inject4 is a placeholder function whose implementation is generated by the 'inject' command.
func Inject4[R1, R2, R3, R4 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4) {
	panic("not implemented")
}

// Inject4E is a placeholder function whose implementation is generated by the 'inject' command.
func Inject4E[R1, R2, R3, R4 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, err error) {
	panic("not implemented")
}

// Inject4C is a placeholder function whose implementation is generated by the 'inject' command.
func Inject4C[R1, R2, R3, R4 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, cleanup func()) {
	panic("not implemented")
}

// Inject4CE is a placeholder function whose implementation is generated by the 'inject' command.
func Inject4CE[R1, R2, R3, R4 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, cleanup func(), err error) {
	panic("not implemented")
}

// Inject5 is a placeholder function whose implementation is generated by the 'inject' command.
func Inject5[R1, R2, R3, R4, R5 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5) {
	panic("not implemented")
}

// Inject5E is a placeholder function whose implementation is generated by the 'inject' command.
func Inject5E[R1, R2, R3, R4, R5 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, err error) {
	panic("not implemented")
}

// Inject5C is a placeholder function whose implementation is generated by the 'inject' command.
func Inject5C[R1, R2, R3, R4, R5 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, cleanup func()) {
	panic("not implemented")
}

// Inject5CE is a placeholder function whose implementation is generated by the 'inject' command.
func Inject5CE[R1, R2, R3, R4, R5 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, cleanup func(), err error) {
	panic("not implemented")
}

// Inject6 is a placeholder function whose implementation is generated by the 'inject' command.
func Inject6[R1, R2, R3, R4, R5, R6 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6) {
	panic("not implemented")
}

// Inject6E is a placeholder function whose implementation is generated by the 'inject' command.
func Inject6E[R1, R2, R3, R4, R5, R6 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6, err error) {
	panic("not implemented")
}

// Inject6C is a placeholder function whose implementation is generated by the 'inject' command.
func Inject6C[R1, R2, R3, R4, R5, R6 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6, cleanup func()) {
	panic("not implemented")
}

// Inject6CE is a placeholder function whose implementation is generated by the 'inject' command.
func Inject6CE[R1, R2, R3, R4, R5, R6 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6, cleanup func(), err error) {
	panic("not implemented")
}

// Inject7 is a placeholder function whose implementation is generated by the 'inject' command.
func Inject7[R1, R2, R3, R4, R5, R6, R7 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6, ret7 R7) {
	panic("not implemented")
}

// Inject7E is a placeholder function whose implementation is generated by the 'inject' command.
func Inject7E[R1, R2, R3, R4, R5, R6, R7 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6, ret7 R7, err error) {
	panic("not implemented")
}

// Inject7C is a placeholder function whose implementation is generated by the 'inject' command.
func Inject7C[R1, R2, R3, R4, R5, R6, R7 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6, ret7 R7, cleanup func()) {
	panic("not implemented")
}

// Inject7CE is a placeholder function whose implementation is generated by the 'inject' command.
func Inject7CE[R1, R2, R3, R4, R5, R6, R7 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6, ret7 R7, cleanup func(), err error) {
	panic("not implemented")
}

// Inject8 is a placeholder function whose implementation is generated by the 'inject' command.
func Inject8[R1, R2, R3, R4, R5, R6, R7, R8 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6, ret7 R7, ret8 R8) {
	panic("not implemented")
}

// Inject8E is a placeholder function whose implementation is generated by the 'inject' command.
func Inject8E[R1, R2, R3, R4, R5, R6, R7, R8 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6, ret7 R7, ret8 R8, err error) {
	panic("not implemented")
}

// Inject8C is a placeholder function whose implementation is generated by the 'inject' command.
func Inject8C[R1, R2, R3, R4, R5, R6, R7, R8 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6, ret7 R7, ret8 R8, cleanup func()) {
	panic("not implemented")
}

// Inject8CE is a placeholder function whose implementation is generated by the 'inject' command.
func Inject8CE[R1, R2, R3, R4, R5, R6, R7, R8 any](ret1 R1, ret2 R2, ret3 R3, ret4 R4, ret5 R5, ret6 R6, ret7 R7, ret8 R8, cleanup func(), err error) {
	panic("not implemented")
}
